Develop
Origin-Byte/originmate pull request #18
Opened 2023-01-11 11:27 UTC by nmboavida

2023-01-11 11:37 UTC, bausano commented on CHANGELOG.md
> +- Updated Sui dep to `0.20.0`
new line here

2023-01-11 11:38 UTC, bausano approved these changes

2023-01-11 11:56 UTC, Suficio requested changes

2023-01-11 11:56 UTC, Suficio commented on sources/object_box.move
> +        dof::remove<TypeName, V>(&mut ob.id, type_name::get<V>())
Length needs to be decremented

2023-01-11 11:56 UTC, Suficio commented on sources/object_box.move
> +        len: u64,
Use bool

2023-01-11 11:56 UTC, Suficio commented on sources/object_box.move
> +    struct ObjectBox has key, store {
If we are releasing this as a library, would be good to rename to `ObjectField` and create a second `Field` which does not require `key`.

Would allow users to mark dynamic fields explicitly.

2023-01-13 11:16 UTC, bausano commented
Could we also have some tests for these

2023-01-13 11:34 UTC, nmboavida commented on sources/object_box.move
> +    struct ObjectBox has key, store {
Added as TODO

2023-01-13 11:34 UTC, nmboavida commented on sources/object_box.move
> +        len: u64,
Added as TODO

2023-01-13 11:50 UTC, Suficio approved these changes

2023-01-13 11:51 UTC, merged